version: 2
updates:
- package-ecosystem: nuget
  target-branch: "dev"
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3

- package-ecosystem: nuget
  target-branch: "v1.4"
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
  ignore:
    - dependency-name: Microsoft.NET.Test.Sdk
      versions:
        - 16.8.3